<a href="https://colab.research.google.com/github/miftahulhdd/MiftahulHudaAmri_2411533005_ML2526/blob/main/praktikum3/TugasLogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, roc_auc_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
dataset_url = 'https://raw.githubusercontent.com/miftahulhdd/MiftahulHudaAmri_2411533005_ML2526/refs/heads/main/praktikum2/Breast_cancer_data.csv'
df = pd.read_csv(dataset_url)
df.head()

X = df.drop('diagnosis', axis=1)
y = df['diagnosis']

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=16)

In [4]:
from sklearn.metrics import accuracy_score

logreg_unscaled = LogisticRegression(random_state=16, max_iter=10000)
logreg_unscaled.fit(X_train, y_train)
y_pred_unscaled = logreg_unscaled.predict(X_test)
acc_unscaled = accuracy_score(y_test, y_pred_unscaled)

In [5]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [6]:
logreg_scaled = LogisticRegression(random_state=16)
logreg_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = logreg_scaled.predict(X_test_scaled)
acc_scaled = accuracy_score(y_test, y_pred_scaled)

In [11]:
print(f"--- Perbandingan Kinerja (Scaling vs Tanpa Scaling) ---")
print(f"Akurasi TANPA Scaling: {acc_unscaled:.4f}")
print(f"Akurasi DENGAN Scaling: {acc_scaled:.4f}")

--- Perbandingan Kinerja (Scaling vs Tanpa Scaling) ---
Akurasi TANPA Scaling: 0.9006
Akurasi DENGAN Scaling: 0.9415


In [8]:
y_pred_proba = logreg_scaled.predict_proba(X_test_scaled)[:, 1]

In [9]:
thresholds = [0.3, 0.5, 0.7]

In [10]:
print("--- Evaluasi Pengaruh Threshold ---")
for thresh in thresholds:
    # Mengubah probabilitas menjadi kelas 0 atau 1 berdasarkan threshold
    y_pred_custom = (y_pred_proba >= thresh).astype(int)

    print(f"\n[ Threshold = {thresh} ]")
    print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_custom))
    print("\nClassification Report:\n", classification_report(y_test, y_pred_custom))

--- Evaluasi Pengaruh Threshold ---

[ Threshold = 0.3 ]

Confusion Matrix:
 [[ 55  10]
 [  1 105]]

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.85      0.91        65
           1       0.91      0.99      0.95       106

    accuracy                           0.94       171
   macro avg       0.95      0.92      0.93       171
weighted avg       0.94      0.94      0.93       171


[ Threshold = 0.5 ]

Confusion Matrix:
 [[ 59   6]
 [  4 102]]

Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.91      0.92        65
           1       0.94      0.96      0.95       106

    accuracy                           0.94       171
   macro avg       0.94      0.93      0.94       171
weighted avg       0.94      0.94      0.94       171


[ Threshold = 0.7 ]

Confusion Matrix:
 [[61  4]
 [11 95]]

Classification Report:
               precision    recall  f1-score   s